"""Reset application data in PostgreSQL for re-seeding.

Only clears tables that are regenerated by the seed script:
- Bookings
- QueueTokens
- Slots
- ProcurementRecords
- Payments

Keeps base data:
- Farmers
- LandRecords
- CultivationRecords
- ProcurementCentres
- Users
"""

import sys
from pathlib import Path

# Add backend to path
backend_path = Path(__file__).resolve().parent / "backend"
sys.path.insert(0, str(backend_path))

from sqlalchemy import text
from app.database.connection import SessionLocal

def reset_imported_data():
    """Clear only the imported application data."""
    print("=" * 60)
    print("RESETTING IMPORTED DATA")
    print("=" * 60)
    
    with SessionLocal() as session:
        try:
            # Delete in order of foreign key dependencies
            print("\nDeleting Payments...")
            session.execute(text("DELETE FROM payments;"))
            print("✓ Payments deleted")
            
            print("Deleting ProcurementRecords...")
            session.execute(text("DELETE FROM procurement_records;"))
            print("✓ ProcurementRecords deleted")
            
            print("Deleting QueueTokens...")
            session.execute(text("DELETE FROM queue_tokens;"))
            print("✓ QueueTokens deleted")
            
            print("Deleting Bookings...")
            session.execute(text("DELETE FROM bookings;"))
            print("✓ Bookings deleted")
            
            print("Deleting Slots...")
            session.execute(text("DELETE FROM slots;"))
            print("✓ Slots deleted")
            
            print("Resetting CultivationRecords.quantity_to_sell_quintals...")
            session.execute(text("""
                UPDATE cultivation_records 
                SET quantity_to_sell_quintals = 0.00
            """))
            print("✓ CultivationRecords reset")
            
            session.commit()
            print("\n" + "=" * 60)
            print("DATA RESET COMPLETED")
            print("=" * 60)
            return True
            
        except Exception as e:
            print(f"\n✗ ERROR: {e}")
            session.rollback()
            return False

if __name__ == "__main__":
    success = reset_imported_data()
    exit(0 if success else 1)
