"""initial schema

Revision ID: adc1c9d7f10b
Revises: 
Create Date: 2026-09-01 20:48:23.867463
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc1c9d7f10b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('farmer_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('passbook_number', sa.String(length=32), nullable=False),
    sa.Column('farmer_name', sa.String(length=120), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=False),
    sa.Column('mandal', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('survey_number', sa.String(length=64), nullable=False),
    sa.Column('total_land_acres', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_land_acres > 0', name=op.f('ck_farmers_positive_land')),
    sa.PrimaryKeyConstraint('farmer_id', name=op.f('pk_farmers')),
    sa.UniqueConstraint('passbook_number', name=op.f('uq_farmers_passbook_number'))
    )
    op.create_index('ix_farmers_latitude_longitude', 'farmers', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_farmers_mobile_number', 'farmers', ['mobile_number'], unique=False)
    op.create_table('procurement_centres',
    sa.Column('centre_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('centre_code', sa.String(length=32), nullable=False),
    sa.Column('centre_name', sa.String(length=160), nullable=False),
    sa.Column('agency', sa.String(length=64), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=False),
    sa.Column('mandal', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_status', sa.String(length=16), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("current_status IN ('ACTIVE', 'LIMITED', 'FULL', 'INACTIVE')", name=op.f('ck_procurement_centres_valid_centre_status')),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_procurement_centres_positive_capacity')),
    sa.PrimaryKeyConstraint('centre_id', name=op.f('pk_procurement_centres')),
    sa.UniqueConstraint('centre_code', name=op.f('uq_procurement_centres_centre_code'))
    )
    op.create_index('ix_procurement_centres_current_status', 'procurement_centres', ['current_status'], unique=False)
    op.create_index('ix_procurement_centres_latitude_longitude', 'procurement_centres', ['latitude', 'longitude'], unique=False)
    op.create_table('cultivation_records',
    sa.Column('cultivation_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('season', sa.String(length=32), nullable=False),
    sa.Column('cultivated_area_acres', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('crop', sa.String(length=64), nullable=False),
    sa.Column('quantity_produced_quintals', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_to_sell_quintals', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cultivated_area_acres > 0', name=op.f('ck_cultivation_records_positive_cultivated_area')),
    sa.CheckConstraint('quantity_produced_quintals > 0', name=op.f('ck_cultivation_records_positive_produced')),
    sa.CheckConstraint('quantity_to_sell_quintals <= quantity_produced_quintals', name=op.f('ck_cultivation_records_sell_not_exceed_produced')),
    sa.CheckConstraint('quantity_to_sell_quintals >= 0', name=op.f('ck_cultivation_records_non_negative_to_sell')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], name=op.f('fk_cultivation_records_farmer_id_farmers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cultivation_id', name=op.f('pk_cultivation_records'))
    )
    op.create_index('ix_cultivation_records_crop', 'cultivation_records', ['crop'], unique=False)
    op.create_index('ix_cultivation_records_farmer_id', 'cultivation_records', ['farmer_id'], unique=False)
    op.create_table('land_records',
    sa.Column('land_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('survey_number', sa.String(length=64), nullable=False),
    sa.Column('land_area_acres', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('land_type', sa.String(length=40), server_default=sa.text("'AGRICULTURAL'"), nullable=False),
    sa.Column('ownership_status', sa.String(length=40), server_default=sa.text("'OWNED'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('land_area_acres > 0', name=op.f('ck_land_records_positive_land_area')),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], name=op.f('fk_land_records_farmer_id_farmers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('land_id', name=op.f('pk_land_records'))
    )
    op.create_index('ix_land_records_farmer_id', 'land_records', ['farmer_id'], unique=False)
    op.create_table('slots',
    sa.Column('slot_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('centre_id', sa.Uuid(), nullable=False),
    sa.Column('slot_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('maximum_farmers', sa.Integer(), nullable=False),
    sa.Column('booked_farmers', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('booked_farmers <= maximum_farmers', name=op.f('ck_slots_booked_within_capacity')),
    sa.CheckConstraint('booked_farmers >= 0', name=op.f('ck_slots_non_negative_booked_farmers')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_slots_slot_end_after_start')),
    sa.CheckConstraint('maximum_farmers > 0', name=op.f('ck_slots_positive_maximum_farmers')),
    sa.ForeignKeyConstraint(['centre_id'], ['procurement_centres.centre_id'], name=op.f('fk_slots_centre_id_procurement_centres'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', name=op.f('pk_slots')),
    sa.UniqueConstraint('centre_id', 'slot_date', 'start_time', name='uq_slots_centre_date_start')
    )
    op.create_index('ix_slots_centre_id_slot_date', 'slots', ['centre_id', 'slot_date'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=True),
    sa.Column('centre_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('FARMER', 'CENTRE_STAFF', 'ADMIN')", name=op.f('ck_users_valid_user_role')),
    sa.ForeignKeyConstraint(['centre_id'], ['procurement_centres.centre_id'], name=op.f('fk_users_centre_id_procurement_centres'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], name=op.f('fk_users_farmer_id_farmers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index('ix_users_centre_id', 'users', ['centre_id'], unique=False)
    op.create_index('ix_users_farmer_id', 'users', ['farmer_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('booking_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('booking_number', sa.String(length=32), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('cultivation_id', sa.Uuid(), nullable=False),
    sa.Column('centre_id', sa.Uuid(), nullable=False),
    sa.Column('slot_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_to_sell_quintals', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('booking_status', sa.String(length=16), server_default=sa.text("'CONFIRMED'"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("booking_status IN ('CONFIRMED', 'CANCELLED', 'COMPLETED', 'NO_SHOW')", name=op.f('ck_bookings_valid_booking_status')),
    sa.CheckConstraint('quantity_to_sell_quintals > 0', name=op.f('ck_bookings_positive_booking_qty')),
    sa.ForeignKeyConstraint(['centre_id'], ['procurement_centres.centre_id'], name=op.f('fk_bookings_centre_id_procurement_centres'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cultivation_id'], ['cultivation_records.cultivation_id'], name=op.f('fk_bookings_cultivation_id_cultivation_records'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], name=op.f('fk_bookings_farmer_id_farmers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.slot_id'], name=op.f('fk_bookings_slot_id_slots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('booking_id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('booking_number', name=op.f('uq_bookings_booking_number'))
    )
    op.create_index('ix_bookings_centre_id', 'bookings', ['centre_id'], unique=False)
    op.create_index('ix_bookings_cultivation_id', 'bookings', ['cultivation_id'], unique=False)
    op.create_index('ix_bookings_farmer_id', 'bookings', ['farmer_id'], unique=False)
    op.create_index('ix_bookings_slot_id', 'bookings', ['slot_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_notifications_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.farmer_id'], name=op.f('fk_notifications_farmer_id_farmers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_farmer_id', 'notifications', ['farmer_id'], unique=False)
    op.create_table('procurement_records',
    sa.Column('procurement_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('quantity_submitted_quintals', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_accepted_quintals', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_per_quintal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('procurement_status', sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('verified_by', sa.Uuid(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("procurement_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'REJECTED')", name=op.f('ck_procurement_records_valid_procurement_status')),
    sa.CheckConstraint('price_per_quintal > 0', name=op.f('ck_procurement_records_positive_price')),
    sa.CheckConstraint('quantity_accepted_quintals <= quantity_submitted_quintals', name=op.f('ck_procurement_records_accepted_not_exceed_submitted')),
    sa.CheckConstraint('quantity_accepted_quintals >= 0', name=op.f('ck_procurement_records_non_negative_accepted')),
    sa.CheckConstraint('quantity_submitted_quintals > 0', name=op.f('ck_procurement_records_positive_submitted')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_procurement_records_booking_id_bookings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.user_id'], name=op.f('fk_procurement_records_verified_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('procurement_id', name=op.f('pk_procurement_records')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_procurement_records_booking_id'))
    )
    op.create_index('ix_procurement_records_verified_by', 'procurement_records', ['verified_by'], unique=False)
    op.create_table('queue_tokens',
    sa.Column('queue_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('token_number', sa.Integer(), nullable=False),
    sa.Column('queue_status', sa.String(length=16), server_default=sa.text("'WAITING'"), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("queue_status IN ('WAITING', 'CALLED', 'PROCESSING', 'COMPLETED', 'SKIPPED', 'CANCELLED')", name=op.f('ck_queue_tokens_valid_queue_status')),
    sa.CheckConstraint('token_number > 0', name=op.f('ck_queue_tokens_positive_token_number')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name=op.f('fk_queue_tokens_booking_id_bookings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('queue_id', name=op.f('pk_queue_tokens')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_queue_tokens_booking_id'))
    )
    op.create_index('ix_queue_tokens_queue_status', 'queue_tokens', ['queue_status'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('procurement_id', sa.Uuid(), nullable=False),
    sa.Column('amount_payable', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=16), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('transaction_reference', sa.String(length=64), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')", name=op.f('ck_payments_valid_payment_status')),
    sa.CheckConstraint('amount_payable >= 0', name=op.f('ck_payments_non_negative_amount')),
    sa.ForeignKeyConstraint(['procurement_id'], ['procurement_records.procurement_id'], name=op.f('fk_payments_procurement_id_procurement_records'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('payment_id', name=op.f('pk_payments')),
    sa.UniqueConstraint('procurement_id', name=op.f('uq_payments_procurement_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_index('ix_queue_tokens_queue_status', table_name='queue_tokens')
    op.drop_table('queue_tokens')
    op.drop_index('ix_procurement_records_verified_by', table_name='procurement_records')
    op.drop_table('procurement_records')
    op.drop_index('ix_notifications_farmer_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_bookings_slot_id', table_name='bookings')
    op.drop_index('ix_bookings_farmer_id', table_name='bookings')
    op.drop_index('ix_bookings_cultivation_id', table_name='bookings')
    op.drop_index('ix_bookings_centre_id', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_farmer_id', table_name='users')
    op.drop_index('ix_users_centre_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_slots_centre_id_slot_date', table_name='slots')
    op.drop_table('slots')
    op.drop_index('ix_land_records_farmer_id', table_name='land_records')
    op.drop_table('land_records')
    op.drop_index('ix_cultivation_records_farmer_id', table_name='cultivation_records')
    op.drop_index('ix_cultivation_records_crop', table_name='cultivation_records')
    op.drop_table('cultivation_records')
    op.drop_index('ix_procurement_centres_latitude_longitude', table_name='procurement_centres')
    op.drop_index('ix_procurement_centres_current_status', table_name='procurement_centres')
    op.drop_table('procurement_centres')
    op.drop_index('ix_farmers_mobile_number', table_name='farmers')
    op.drop_index('ix_farmers_latitude_longitude', table_name='farmers')
    op.drop_table('farmers')
    # ### end Alembic commands ###
